<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WorkPulse.Contracts\WorkPulse.Contracts.csproj" />
      <ProjectReference Include="..\WorkPulse.Entities\WorkPulse.Entities.csproj" />
    </ItemGroup>

</Project>
